#!/bin/sh
# was used for a 60 % keyboard i had
setxkbmap -option caps:super
xmodmap -e "keycode 49 = Escape"
xmodmap -e "keycode 9 = grave asciitilde"
xmodmap -e "keycode 135 = NoSymbol"
xmodmap -e "keycode 22 = BackSpace Delete"
xinput --disable "SynPS/2 Synaptics TouchPad"
