#!/bin/sh
xrandr --output HDMI-A-0 --mode 1280x720
xrandr --output eDP --mode 1280x720
# xrandr --output HDMI-A-0 --scale 0.7x0.7
# xrandr --output eDP --scale 0.7x0.7
killall -q polybar
if [ "$1" -gt "-1" ]
then
	xrandr --output HDMI-A-0 --auto --right-of eDP
	bspc monitor eDP -d 6 7 8 9 0
	bspc monitor HDMI-A-0 -d 1 2 3 4 5
	bspc config -m HDMI-A-0  top_padding 20
	# xrandr --output HDMI-A-0 --auto --left-of eDP
	polybar left     &
	polybar right	 &
	polybar center   &
	polybar left_s   &
	polybar right_s  &
	polybar center_s &
	nitrogen --head=0 --set-zoom-fill /home/catalin/Pictures/wallpapers/landscape/ilustr_7.jpg
	nitrogen --head=1 --set-zoom-fill /home/catalin/Pictures/wallpapers/landscape/ilustr_6.jpg
else
	xrandr --output HDMI-A-0 --same-as eDP
	bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 0 
	polybar left     &
	polybar right	 &
	polybar center   &
	nitrogen --restore
fi
