#!/bin/sh
xrandr --output HDMI-A-0 --mode 1280x720
xrandr --output eDP --mode 1280x720
# xrandr --output HDMI-A-0 --scale 0.7x0.7
# xrandr --output eDP --scale 0.7x0.7
if [ "$1" -gt "-1" ]
then
	xrandr --output HDMI-A-0 --auto --right-of eDP
	# xrandr --output HDMI-A-0 --auto --left-of eDP
	nitrogen --head=0 --set-zoom-fill /home/catalin/Pictures/wallpapers/landscape/ilustr_7.jpg
	nitrogen --head=1 --set-zoom-fill /home/catalin/Pictures/wallpapers/landscape/ilustr_6.jpg
else
	xrandr --output HDMI-A-0 --same-as eDP
	nitrogen --restore
fi
