#!/bin/sh
xrandr --output eDP --mode 1280x720
if [ "$1" -gt "-1" ]
then
	xrandr --output HDMI-A-0 --auto --right-of eDP --primary --mode 1280x720
	nitrogen --head=0 --set-zoom-fill /home/catalin/Pictures/wallpapers/landscape/ilustr_7.jpg
	nitrogen --head=1 --set-zoom-fill /home/catalin/Pictures/wallpapers/landscape/ilustr_6.jpg
else
	xrandr --output HDMI-A-0 --same-as eDP
	nitrogen --restore
fi
