#!/bin/bash

hostname=$(hostname)

case "$hostname" in
    "workstation"|"a520mkv2")
		dirs=(
			"/home/catalin/.config/"
			"/home/catalin/scripts/"
			"/home/catalin/dev/ErgoType/"
			"/home/catalin/dev/read"
		)
        ;;
    "laptop"|"catalin-ThinkPad-E595")
        dirs=(
            "/home/catalin/.config/"
            "/home/catalin/scripts/"
            "/home/catalin/dev/ergotype.2/"
            "/home/catalin/dev/read.2"
        )
        ;;
    *)
        # Default configuration
        dirs=(
            "/home/catalin/.config/"
            "/home/catalin/scripts/"
        )
        ;;
esac
